# Generated by Django 3.1 on 2020-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20200918_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_bench_spots',
            field=models.PositiveIntegerField(verbose_name='Bench Spots'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_cornerbacks',
            field=models.PositiveIntegerField(verbose_name='Cornerbacks'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_defensive_backs',
            field=models.PositiveIntegerField(verbose_name='Defensive Backs'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_defensive_ends',
            field=models.PositiveIntegerField(verbose_name='Defensive Ends'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_defensive_lines',
            field=models.PositiveIntegerField(verbose_name='Defensive Lines'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_defensive_players',
            field=models.PositiveIntegerField(verbose_name='Defensive Players'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_defensive_tackles',
            field=models.PositiveIntegerField(verbose_name='Defensive Tackles'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_edge_rushers',
            field=models.PositiveIntegerField(verbose_name='Edge Rushers'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_flex_running_back_wide_receiver',
            field=models.PositiveIntegerField(verbose_name='Flex RB/WR'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_flex_running_back_wide_receiver_tight_end',
            field=models.PositiveIntegerField(verbose_name='Flex RB/WR/TE'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_flex_wide_receiver_tight_end',
            field=models.PositiveIntegerField(verbose_name='Flex WR/TE'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_head_coaches',
            field=models.PositiveIntegerField(verbose_name='Head Coaches'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_injured_reserve_spots',
            field=models.PositiveIntegerField(verbose_name='Injured Reserve Spots'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_kickers',
            field=models.PositiveIntegerField(verbose_name='Kickers'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_linebackers',
            field=models.PositiveIntegerField(verbose_name='Linebackers'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_offensive_players',
            field=models.PositiveIntegerField(verbose_name='Offensive Players'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_punters',
            field=models.PositiveIntegerField(verbose_name='Punters'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_quarterbacks',
            field=models.PositiveIntegerField(verbose_name='Quarterbacks'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_running_backs',
            field=models.PositiveIntegerField(verbose_name='Running Backs'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_safeties',
            field=models.PositiveIntegerField(verbose_name='Safeties'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_team_defense_special_teams',
            field=models.PositiveIntegerField(verbose_name='Defense / Special Teams'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_team_quarterbacks',
            field=models.PositiveIntegerField(verbose_name='Team Quarterbacks'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_tight_ends',
            field=models.PositiveIntegerField(verbose_name='Tight Ends'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='roster_wide_receivers',
            field=models.PositiveIntegerField(verbose_name='Wide Receivers'),
        ),
    ]
