# Generated by Django 3.1 on 2020-09-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20200919_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='projections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50, verbose_name='Player Team')),
                ('position', models.CharField(max_length=5)),
                ('passing_attempts', models.FloatField()),
                ('passing_completions', models.FloatField()),
                ('passing_yards', models.FloatField()),
                ('passing_touchdowns', models.FloatField()),
                ('passing_interceptions', models.FloatField()),
                ('rushing_attempts', models.FloatField()),
                ('rushing_yards', models.FloatField()),
                ('rushing_touchdowns', models.FloatField()),
                ('receiving_receptions', models.FloatField()),
                ('receiving_yards', models.FloatField()),
                ('receiving_touchdowns', models.FloatField()),
                ('player_fumbles_lost', models.FloatField()),
                ('kicking_field_goals_attempted', models.FloatField()),
                ('kicking_field_goals_made', models.FloatField()),
                ('kicking_extra_points_made', models.FloatField()),
                ('dst_sacks', models.FloatField()),
                ('dst_interceptions', models.FloatField()),
                ('dst_fumbles_recovered', models.FloatField()),
                ('dst_fumbles_forced', models.FloatField()),
                ('dst_touchdowns', models.FloatField()),
                ('dst_safeties', models.FloatField()),
                ('dst_points_against', models.FloatField()),
                ('dst_yards_against', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'projections',
                'ordering': ('player',),
            },
        ),
        migrations.AlterModelOptions(
            name='leaguesettings',
            options={'ordering': ('title',), 'verbose_name_plural': 'league settings'},
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_0_points_allowed',
            field=models.FloatField(verbose_name='Points For 0 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_14_to_17_points_allowed',
            field=models.FloatField(verbose_name='Points For 14-17 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_14_to_20_points_allowed',
            field=models.FloatField(verbose_name='Points For 14-20 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_18_to_21_points_allowed',
            field=models.FloatField(verbose_name='Points For 18-21 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_1_to_6_points_allowed',
            field=models.FloatField(verbose_name='Points For 1-6 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_21_to_27_points_allowed',
            field=models.FloatField(verbose_name='Points For 21-27 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_22_to_27_points_allowed',
            field=models.FloatField(verbose_name='Points For 22-27 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_28_to_34_points_allowed',
            field=models.FloatField(verbose_name='Points For 28-34 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_35_to_45_points_allowed',
            field=models.FloatField(verbose_name='Points For 35-45 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_46_or_more_points_allowed',
            field=models.FloatField(verbose_name='Points For 46+ Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_7_to_13_points_allowed',
            field=models.FloatField(verbose_name='Points For 7-13 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_blocked_punt_or_field_goal_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Blocked Punt or Field Goal Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_blocked_punt_point_after_touchdown_field_goal',
            field=models.FloatField(verbose_name='Points Per Blocked Extra Point'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_extra_points_returned',
            field=models.FloatField(verbose_name='Points Per Blocked Extra Point Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_fumble_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Fumble Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_fumbles_recovered',
            field=models.FloatField(verbose_name='Points Per Fumble Recovered'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_interception_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Interception Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_interceptions',
            field=models.FloatField(verbose_name='Points Per Interception'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_kickoff_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Kickoff Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_punt_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Punt Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_sacks',
            field=models.FloatField(verbose_name='Points Per Sack'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_safeties',
            field=models.FloatField(verbose_name='Points Per Safety'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_fumble_recovered_touchdowns',
            field=models.FloatField(verbose_name='Points Per Player Fumble Returned for a Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_fumbles_lost',
            field=models.FloatField(verbose_name='Points Per Player Fumble Lost'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_kickoff_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Player Kickoff Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_punt_return_touchdowns',
            field=models.FloatField(verbose_name='Points Per Player Punt Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_0_to_39',
            field=models.FloatField(verbose_name='Points Per 0-39 Yard Field Goal Made'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_40_to_49',
            field=models.FloatField(verbose_name='Points Per 40-49 Yard Field Goal Made'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_50_to_59',
            field=models.FloatField(verbose_name='Points Per 50-59 Yard Field Goal Made'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_60_or_more',
            field=models.FloatField(verbose_name='Points Per 60+ Yard Field Goal Made'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_0_to_39',
            field=models.FloatField(verbose_name='Points Per 0-39 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_40_to_49',
            field=models.FloatField(verbose_name='Points Per 40-49 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_50_to_59',
            field=models.FloatField(verbose_name='Points Per 50-59 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_60_or_more',
            field=models.FloatField(verbose_name='Points Per 60+ Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_point_after_touchdowns',
            field=models.FloatField(verbose_name='Points Per Point After Touchdown Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_point_after_touchdowns',
            field=models.FloatField(verbose_name='Points Per Point After Touchdown Made'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_receptions',
            field=models.FloatField(verbose_name='Points Per Reception'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_touchdowns',
            field=models.FloatField(verbose_name='Points Per Receiving Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_two_point_conversions',
            field=models.FloatField(verbose_name='Points Per Receiving Two Point Conversion'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_yards',
            field=models.FloatField(verbose_name='Points Per Receiving Yard'),
        ),
    ]
