# Generated by Django 3.1 on 2020-09-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20200921_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(
                    max_length=4, unique=True, verbose_name='Team Abbr')),
                ('name', models.CharField(max_length=25, verbose_name='Team')),
                ('mascot', models.CharField(max_length=20)),
                ('bye_week', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='projections',
            name='team',
            field=models.CharField(max_length=4)
        ),
    ]
