# Generated by Django 3.1 on 2020-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20200923_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_0_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 0 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_14_to_17_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 14-17 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_14_to_20_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 14-20 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_18_to_21_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 18-21 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_1_to_6_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 1-6 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_21_to_27_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 21-27 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_22_to_27_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 22-27 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_28_to_34_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 28-34 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_35_to_45_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 35-45 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_46_or_more_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 46+ Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_7_to_13_points_allowed',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points For 7-13 Points Allowed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_blocked_punt_or_field_goal_return_touchdowns',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Blocked Punt or Field Goal Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_blocked_punt_point_after_touchdown_field_goal',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Blocked Extra Point'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_extra_points_returned',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Blocked Extra Point Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_fumble_return_touchdowns',
            field=models.FloatField(verbose_name='DEFENSE/SPECIAL TEAMS - Points Per Fumble Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_fumbles_recovered',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Fumble Recovered'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_interception_return_touchdowns',
            field=models.FloatField(verbose_name='DEFENSE/SPECIAL TEAMS - Points Per Interception Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_interceptions',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Interception'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_kickoff_return_touchdowns',
            field=models.FloatField(verbose_name='DEFENSE/SPECIAL TEAMS - Points Per Kickoff Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_punt_return_touchdowns',
            field=models.FloatField(verbose_name='DEFENSE/SPECIAL TEAMS - Points Per Punt Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_sacks',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Sack'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='dst_safeties',
            field=models.FloatField(verbose_name='TEAM DEFENSE/SPECIAL TEAMS - Points Per Safety'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_fumble_recovered_touchdowns',
            field=models.FloatField(verbose_name='MISC PLAYER - Points Per Fumble Returned for a Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_fumbles_lost',
            field=models.FloatField(verbose_name='MISC PLAYER - Points Per Fumble Lost'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_kickoff_return_touchdowns',
            field=models.FloatField(verbose_name='MISC PLAYER - Points Per Kickoff Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='individual_player_punt_return_touchdowns',
            field=models.FloatField(verbose_name='MISC PLAYER - Points Per Punt Return Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_0_to_39',
            field=models.FloatField(verbose_name='KICKING - Points Per 0-39 Yard Field Goal'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_40_to_49',
            field=models.FloatField(verbose_name='KICKING - Points Per 40-49 Yard Field Goal'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_50_to_59',
            field=models.FloatField(verbose_name='KICKING - Points Per 50-59 Yard Field Goal'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_field_goal_60_or_more',
            field=models.FloatField(verbose_name='KICKING - Points Per 60+ Yard Field Goal'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_0_to_39',
            field=models.FloatField(verbose_name='KICKING - Points Per 0-39 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_40_to_49',
            field=models.FloatField(verbose_name='KICKING - Points Per 40-49 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_50_to_59',
            field=models.FloatField(verbose_name='KICKING - Points Per 50-59 Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_field_goal_60_or_more',
            field=models.FloatField(verbose_name='KICKING - Points Per 60+ Yard Field Goal Missed'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_missed_point_after_touchdowns',
            field=models.FloatField(verbose_name='KICKING - Points Per Missed Extra Point'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='kicking_point_after_touchdowns',
            field=models.FloatField(verbose_name='KICKING - Points Per Extra Point'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='passing_interceptions',
            field=models.FloatField(verbose_name='PASSING - Points Per Interception'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='passing_touchdowns',
            field=models.FloatField(verbose_name='PASSING - Points Per Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='passing_two_point_conversions',
            field=models.FloatField(verbose_name='PASSING - Points Per Two Point Conversion'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='passing_yards',
            field=models.FloatField(verbose_name='PASSING - Points Per Yard'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_receptions',
            field=models.FloatField(verbose_name='RECEIVING - Points Per Reception'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_touchdowns',
            field=models.FloatField(verbose_name='RECEIVING - Points Per Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_two_point_conversions',
            field=models.FloatField(verbose_name='RECEIVING - Points Per Two Point Conversion'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='receiving_yards',
            field=models.FloatField(verbose_name='RECEIVING - Points Per Yard'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='rushing_touchdowns',
            field=models.FloatField(verbose_name='RUSHING - Points Per Touchdown'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='rushing_two_point_conversions',
            field=models.FloatField(verbose_name='RUSHING - Points Per Two Point Conversion'),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='rushing_yards',
            field=models.FloatField(verbose_name='RUSHING - Points Per Yard'),
        ),
        migrations.AlterField(
            model_name='projections',
            name='player',
            field=models.CharField(max_length=50),
        ),
    ]
