# Generated by Django 3.1 on 2020-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20201008_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
