# Generated by Django 3.1 on 2020-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_auto_20201008_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='MultiplePositionRosterSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('positions', models.ManyToManyField(to='football.Position')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
